// Copyright (c) 2022 James Reid. All rights reserved.
//
// This source code file is licensed under the terms of the MIT license, a copy
// of which may be found in the LICENSE.md file in the root of this repository.  
// 
// For a template copy of the license see one of the following 3rd party sites:
//      * <https://opensource.org/licenses/MIT>
//      * <https://choosealicense.com/licenses/mit>
//      * <https://spdx.org/licenses/MIT>

// @ts-check

/**
 * @file NestedModule type declaration
 * @author James Reid
 */

// @body
/**
 *  This is a test
 * 
 * @summary test
 * @typedef {object} NestedModule
 * @property {string} name - Name of module or member etc.
 * @property {string} href - Link of module or member etc. as used in the jsdoc
 *      autogenerated output; all links are top level
 * @property {string} type - 
 * @property {string} hierarchy -
 * @property {string} path - 
 * @property {NestedModule[]} children - Array of submodules
 * @property {string} [access] - Access of member if exists
 * @property {string} [scope] - Scope of member if exists
 */

// @exports
/**
 * @ignore
 * @type {NestedModule} 
 */
export let NestedModule